### ISSUE TITLE
linemux::MuxedLines::next() appears to stop relaying changes after a period

### ISSUE THREAD

**Issue by happybeing** [jmagnuson/linemux#17] opened 2020-09-09 16:03 UTC
This may not be linemux, but as its hard to isolate I'm reporting this in case others see something similar. I'm using tokio async futures, and only testing on Ubuntu 20 at the moment, and see this after successfully using linemux to track a logfile which I then display in a terminal UI.

To reproduce this you can install [logtail](https://crates.io/crates/logtail) and leave it monitoring a system logfile (in the manner of `tail -f`) and eventually it will no longer receive updates from the async future.

The loop is here:

https://github.com/theWebalyst/logtail-dash/blob/master/src/bin/logtail-termion.rs#L116-L119

I'm actually debugging using a different app (a fork of logtail) which has the same behaviour, and what I've diagnosed is that after some unknown period of time (once less than an hour, sometimes maybe much more) I no longer reach this point, which may mean that there's an issue in `linemux`:

https://github.com/theWebalyst/logtail-dash/blob/master/src/bin/logtail-termion.rs#L148

**Comment by jmagnuson** [comment] 2020-09-10 03:55
I suspect the issue is with the event channel:

https://github.com/theWebalyst/logtail-dash/blob/1dc4bf11e40060068bcaeccb68e544e6f82fe505/src/event.rs#L21

and its usage within an async context:

https://github.com/theWebalyst/logtail-dash/blob/1dc4bf11e40060068bcaeccb68e544e6f82fe505/src/bin/logtail-termion.rs#L166

Using `std::sync::mpsc` Receiver will block the thread that tokio runs on. Instead, tokio provides its own `mpsc` channel that can be used to avoid this, with a blurb on [choosing a channel](https://docs.rs/tokio/0.2.22/tokio/sync/mpsc/index.html#communicating-between-sync-and-async-code):

>You should use the kind of channel that matches where the receiver is. So for sending a message from async to sync, you should use the standard library unbounded channel or crossbeam. Similarly, for sending a message from sync to async, you should use an unbounded Tokio mpsc channel.

**Comment by happybeing** [comment] 2020-09-12 13:01
Thanks very much again for the extra level help you give. I've modified the events channel and now soak-testing it.

UPDATE:
@jmagnuson my test shows that linemux doesn't handle logfile rotation, is that a known limitation? 

In my test using the tokio mpsc as you suggested, I've just observed that linemux stops updating once the logfile has been rotated. I was fairly sure this wasn't the only issue, but need to look into that using a different test.

**Comment by jmagnuson** [comment] 2020-09-14 16:15
linemux was initially designed for truncation-based file rotation (`tail -f`), but I definitely do want to support renames (`tail -F`) which I believe is what `logrotate` is doing-- is that what you’re testing with? It will be tricky due to various limitations, but should (🤞) be feasible without resorting to polling (hopefully for other non-linux platforms as well).

I'll be pretty strapped for time all this week, but should (again, 🤞) be able to take a look over the next weekend.

**Comment by happybeing** [comment] 2020-09-14 19:46
I'm not familiar with `logrotate` or the various flavours so will have to read up on this, and have just been testing with the logfiles in /var/log (Ubuntu).

I'm not in a hurry, but it will certainly enhance `logtail`. It was just a Rust learning project but turns out to be useful so I'd like to fix this, and if you have plans to support this that would be great.

**Comment by EbonJaeger** [comment] 2020-10-31 00:44
I think my use-case (`tail -F` I believe?) is related to this issue: The file I'm watching gets moved and recreated. I'd love to help out and implement it, but I am unsure of the best place to do it. I would guess that the way to do it would be to unregister the path in the state and re-`insert_pending()` it based on a `notify` event, and then wait for a new file at that path to be created.

**Comment by jmagnuson** [comment] 2020-10-31 19:50
So here:

https://github.com/jmagnuson/linemux/blob/21cfee16fe4c8c5029df8f39066b1a2240898c2e/src/events.rs#L192

pending/watched logic is checked against the path existence of the time of the call. This was done I think to avoid relying on certain event types across platforms. However, this introduces a race where we could be doing a path check could be misaligned with where something like `logrotate` is at in its rotation, as well as filesystem synchronization. Here is the output of running `lines /var/log/messages` (with extra `println!`s) against a call to `logrotate -vf /etc/logrotate.d/syslog-ng` which forces log rotation:

```
Event { kind: Modify(Name(From)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
removing watched file: "/var/log/messages"
adding file to pending
Event { kind: Modify(Data(Any)), paths: ["/var/log/messages.1"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Remove(File), paths: ["/var/log/messages.1"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Metadata(Any)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/messages.1"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Create(File), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
adding pending watched file: "/var/log/messages"
adding file to watched
(/var/log/messages) Oct 31 13:48:34 r4 syslog-ng[23415]: Configuration reload request received, reloading configuration;
(/var/log/messages) Oct 31 13:48:34 r4 syslog-ng[23415]: Configuration reload finished;
Event { kind: Modify(Metadata(Any)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Access(Close(Write)), paths: ["/var/log/messages.1"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Access(Close(Write)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Remove(File), paths: ["/var/log/messages"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

I think forcing `path_exists = false` on event `EventKind::Remove(RemoveKind::File)` should help sync the file states. Not perfect, but should at least work in the linux + `logrotate` case.

**Comment by EbonJaeger** [comment] 2020-10-31 21:35
That does indeed work with what I use it for! And is a bit simpler than what I was thinking. As usual. lol

Do some log rotation strategies rename the file instead of deleting it? I covered this case in my changes, but I'm not sure if it's necessary.

**Comment by jmagnuson** [comment] 2020-11-01 03:41
@EbonJaeger shoot, were you going to submit a PR for the fix? I just created #19 which only does what I described above, but if you have something more comprehensive I'd love to see it. Either way, thanks for the confirmation!

`logrotate` does actually do a `rename` by default; here's the `strace` of it in action:

```
22:04:48.499052 stat("/var/log/messages", {st_mode=S_IFREG|0600, st_size=169, ...}) = 0 <0.000011>
22:04:48.499094 write(2, "renaming /var/log/messages to /v"..., 50renaming /var/log/messages to /var/log/messages.1
) = 50 <0.000012>
22:04:48.499132 rename("/var/log/messages", "/var/log/messages.1") = 0 <0.000036>
```

The main alternative I'm aware of is is the truncation method which `linemux` should already support. And `logrotate` can in fact use this method via the non-default `copytruncate` option, but it has its own share of potential [race issues](https://incoherency.co.uk/blog/stories/logrotate-copytruncate-race-condition.html).

**Comment by EbonJaeger** [comment] 2020-11-01 04:05
@jmagnuson I was, but it's no big deal xD

Here is what I came up with:
It's a bit longer with the `match` branching; I didn't think to just set `path_exists` like you did... Your way does simplify things quite a bit, which is nice!
```rust
match &event.kind {
    // Handle file deletion, e.g. for log rotation
    notify::EventKind::Remove(_) => {
        path_exists = false;
    }
    // Handle file modifications
    notify::EventKind::Modify(kind) => match kind {  > &ModifyKind
        // Some log rotation strategies might rename the file instead of deleting them
        notify::event::ModifyKind::Name(_) => {
            path_exists = false;
        }
        // Handle all other modification events
        _ => {}
    },
    // Handle file creation events so we can add watched files
    notify::event::EventKind::Create(_) => {
        if path_exists && self.pending_watched_files.contains(path) {
            let parent = path.parent().expect("Pending watched file needs
            let _ = self.remove_directory(parent);  > path
            self.pending_watched_files.remove(path);
            let _ = self.add_file(path);
        }
    }
    _ => {}
}
```

EDIT: There's also this version that might be less convoluted than what I posted last night:
```rust
let path_exists =
    if let notify::EventKind::Remove(notify::event::RemoveKind::File) = &event.kind {
        false
    } else if let notify::EventKind::Modify(notify::event::ModifyKind::Name(_)) =
        &event.kind
    {
        false
    } else {
        path.exists()
    };

// Handle file creation events so we can add watched files
if let notify::event::EventKind::Create(notify::event::CreateKind::File) = &event.kind {
     if path_exists && self.pending_watched_files.contains(path) {
        let parent = path.parent().expect("Pending watched file needs a parent");
        let _ = self.remove_directory(parent);
        self.pending_watched_files.remove(path);
        let _ = self.add_file(path);
    }
}
```

**Comment by jmagnuson** [comment] 2020-11-08 04:28
Ah, yeah handling `Create` is probably a good idea and could save on some calls to `path.exists()`. I'll play around with that idea after the `Remove` PR is merged, but for the time-being, the latter call serves as a decent catchall for adding pending watched files.

I believe with how `notify` (+ `inotify` at least) works, it dispatches both the `Modify(Name)` as well as `Remove(File)` for every file rename, so we'd end up unwatching the file multiple times per trigger. Shouldn't break things more than they already are not handling anything, but that's another thing I'd like to play around with and see what works best for all platforms.

**Comment by jmagnuson** [comment] 2020-11-08 05:36
Just published version [0.1.2](https://crates.io/crates/linemux/0.1.2) which includes the proposed fix to this. Let me know if there are still any issues with log rotation!

**Comment by happybeing** [comment] 2020-11-08 10:36
Awesome, thank you again for linemux! I'll try this out soon.

**Comment by EbonJaeger** [comment] 2020-11-08 15:49
Confirmed working for my case. Thanks!!

**Comment by happybeing** [comment] 2020-11-11 12:52
I bumped linemux to 0.1.2 (and tokio to 0.2.22 which required I add tokio-macros explicitly) and I believe I still have the issue (only tested on Ubuntu 20.10 so far).

I left logtail ([crates.io](https://crates.io/crates/logtail)) monitoring /var/log/syslog and /var/log/kern.log and all seemed fine after 24 hours including with laptop suspend/resume overnight, but a day later (so 48 hours-ish) after I resumed things seemed ok at first but soon after are not updating.

What I saw in the logtail display is:

- both logs showed events up to the time I had just resumed from suspend
- but further updates are no longer happening

One factor to consider is that I left two copies of logtail running yesterday side by side monitoring the same files. I do this so I can check what the first should display be re-starting the second, but maybe that creates an unnecessary complication.

The second copy of logtail correctly shows and updates the log file content.

Could be an edge case, maybe to do with suspending and resuming the OS.

**Comment by happybeing** [comment] 2020-11-14 12:06
UPDATE: three days since the above reply when I left the original and a newly started instance running, the first instance has remained not, updated but the second is still updating after three laptop suspend/resume cycle so let's leave this closed and see if it crops up enough from other situations to be an issue. I'll leave things running and see how long it continues to be ok.

**Comment by jmagnuson** [comment] 2020-11-14 17:28
Thanks for the update! Meant to mention-- I didn't have a bare-metal Ubuntu laptop handy, so tried to reproduce on a VM and couldn't. But if anything new emerges feel free to reopen or create a new issue.

**Comment by happybeing** [comment] 2020-11-15 18:48
It's still stopping when the logfile is moved. I noticed that while I have logtail monitoring both /var/log/syslog and /vat/log/kern.log, the former had stopped yesterday at this line:

`Nov 14 12:01:27 laptoop systemd[1]: Finished Daily man-db regeneration.`

And doing tail /var/log/syslog.1 shows that this was the last line in /var/log/syslog.1. You should be able to test this if you `cargo install logtail`

**Comment by jmagnuson** [comment] 2020-11-18 04:43
Figured out log rotation on my VM tonight and was able to reproduce. Turns out @EbonJaeger was right on the money by suggesting handling both `Remove` and `Modify(Name)`, as I'm not seeing the former show up in Ubuntu's log rotation for some reason:

<details><summary>lines 0.2.1</summary>
<p>

```
jon@yoctodev:~/src/rust/linemux$ cargo run --example lines /var/log/syslog /var/log/auth.log
   Compiling linemux v0.1.2 (/home/jon/src/rust/linemux)
    Finished dev [unoptimized + debuginfo] target(s) in 1.54s
     Running `target/debug/examples/lines /var/log/syslog /var/log/auth.log`
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:08 yoctodev jon: uhohawf2f2f2f23f23f
Event { kind: Modify(Data(Any)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/auth.log) Nov 17 22:16:19 yoctodev sudo:      jon : TTY=pts/2 ; PWD=/home/jon ; USER=root ; COMMAND=/usr/sbin/logrotate -f /etc/logrotate.conf
(/var/log/auth.log) Nov 17 22:16:19 yoctodev sudo: pam_unix(sudo:session): session opened for user root by jon(uid=0)
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopping Make remote CUPS printers available locally...
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopped Make remote CUPS printers available locally.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopping CUPS Scheduler...
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopped CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopped CUPS Scheduler.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopping CUPS Scheduler.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Started CUPS Scheduler.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Closed CUPS Scheduler.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Stopping CUPS Scheduler.
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Listening on CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Started CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:16:19 yoctodev systemd[1]: Started Make remote CUPS printers available locally.
Event { kind: Modify(Name(From)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Access(Close(Write)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Access(Close(Write)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Name(From)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

</p>
</details>

<details><summary>lines 0.2.1 + handle <code>Modify(Name)</code></summary>
<p>

```
jon@yoctodev:~/src/rust/linemux$ cargo run --example lines /var/log/syslog /var/log/auth.log
   Compiling linemux v0.1.2 (/home/jon/src/rust/linemux)
    Finished dev [unoptimized + debuginfo] target(s) in 1.40s
     Running `target/debug/examples/lines /var/log/syslog /var/log/auth.log`
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:45 yoctodev jon: hasdfasd
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:50 yoctodev jon: uhohawf2f2f2f23f23f
Event { kind: Modify(Data(Any)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/auth.log) Nov 17 22:22:54 yoctodev sudo:      jon : TTY=pts/2 ; PWD=/home/jon/src/rust/linemux ; USER=root ; COMMAND=/usr/sbin/logrotate -f /etc/logrotate.conf
Event { kind: Modify(Data(Any)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/auth.log) Nov 17 22:22:54 yoctodev sudo: pam_unix(sudo:session): session opened for user root by jon(uid=0)
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopping Make remote CUPS printers available locally...
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopped Make remote CUPS printers available locally.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopping CUPS Scheduler...
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopped CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopped CUPS Scheduler.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopping CUPS Scheduler.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Started CUPS Scheduler.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Closed CUPS Scheduler.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Stopping CUPS Scheduler.
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Listening on CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Started CUPS Scheduler.
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:54 yoctodev systemd[1]: Started Make remote CUPS printers available locally.
Event { kind: Modify(Name(From)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Removed /var/log/syslog, res: Ok("/var/log/syslog")
Event { kind: Access(Close(Write)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Access(Close(Write)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Event { kind: Modify(Name(From)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
Removed /var/log/auth.log, res: Ok("/var/log/auth.log")
Event { kind: Modify(Data(Any)), paths: ["/var/log/auth.log"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/auth.log) Nov 17 22:22:55 yoctodev sudo: pam_unix(sudo:session): session closed for user root
Event { kind: Modify(Data(Any)), paths: ["/var/log/syslog"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
(/var/log/syslog) Nov 17 22:22:58 yoctodev jon: hasdfasd
```

</p>
</details>

I'll do a bit more testing on my machine (which AFAIK is still emitting both events), but this should be the final fix for this 🤞

Edit -- There's also another race that I probably shouldn't pretend doesn't exist: the way this fix works with the patch is that once we hit the watch-to-pending branch with `Modify(Name)`, `self.add_file()` is supposed to be the one to add the file to the pending map. But in reality, the file exists by the time we get to the second `path.exists()` call, so `add_file` effectively short-circuits the wait for event `Create` which we apparently don't get anyway.

Rotation strace for posterity:

```
19922 23:15:04.700663 openat(AT_FDCWD, "/var/log/syslog", O_RDONLY|O_NOFOLLOW) = 3 <0.000142>
19922 23:15:04.701001 close(3)          = 0 <0.000112>
19922 23:15:04.701286 getxattr("/var/log/syslog", "system.posix_acl_access", 0x7ffc336afb50, 132) = -1 ENODATA (No data available) <0.000115>
19922 23:15:04.701594 stat("/var/log/syslog", {st_mode=S_IFREG|0640, st_size=1859, ...}) = 0 <0.000167>
19922 23:15:04.702010 rename("/var/log/syslog", "/var/log/syslog.1") = 0 <0.000183>
19922 23:15:04.702393 openat(AT_FDCWD, "/var/log/syslog", O_RDWR|O_CREAT|O_EXCL|O_NOFOLLOW, 0600) = 3 <0.000187>
19922 23:15:04.702773 fchmod(3, 0600)   = 0 <0.000141>
```

**Comment by jmagnuson** [comment] 2020-11-22 18:05
Just published version [0.1.3](https://crates.io/crates/linemux/0.1.3). @happybeing would you mind trying this out with `logtail`?

**Comment by happybeing** [comment] 2020-11-25 11:17
Looks good, it has survived one syslog rotation! Will leave it running, suggest closing this now and thanks for this :clap:

**Closed as completed** 2020-11-25 15:32 UTC

**Comment by happybeing** [comment] 2020-12-17 13:05
I'm afraid this can still fail - eventually - for me on Ubuntu. It has been running for about three weeks but failed two days ago on /var/log/syslog rotation.

I have had logtail watching /var/log/syslog and /var/log/kern.log during the entire period (since at least 22 days ago). The latter is still going, while /var/log/syslog stopped updating on Dec 15 at the last message in a rotated log. 

So it is definitely still coincident with a log rotation, although not every log rotation as many have happened during those weeks. /var/log/syslog log looks to rotate about once per day, so that's quite a lot of successful rotations.

I wonder if it is to do with when the rotation happens, such as close to when I sleep or wake my laptop, as this is something I do daily but I've no evidence to support that. I just can't think of what might be happening now.

This isn't a major issue for me although it would be nice to have fixed.
